ssis/models/college.py
from . import cursor, db


class College:
    def __init__(
        self, 
        code: str = None,
        name: str = None
    ):
        
        self.code = code
        self.name = name


    def get_all(
        self, 
        page_num: int = None, 
        item_per_page: int = None, 
        paginate: bool = True
    ):
        
        if not paginate:
            return self.college_list()
        
        offset = (page_num - 1) * item_per_page
        
        query = f'''
            SELECT 
                college.code, 
                college.name, 
                COUNT(*) as courses
            FROM college
            JOIN course
                ON college.code = course.college
            LEFT JOIN (
                SELECT 
                    collegecode, 
                    COUNT(*) as student
                FROM students
                GROUP BY collegecode
            ) enrolled

            ON college.code = enrolled.collegecode
            GROUP BY college.code

            LIMIT {item_per_page} OFFSET {offset}
        '''
        
        cursor.execute(query)
        result = cursor.fetchall()
        
        colleges = [list(college) for college in result]
        college_codes = [code[0] for code in colleges]
        
        all_colleges = self.college_list()
        for college in all_colleges:
            c_code = college[0]
            if c_code not in college_codes:
                colleges.append([c_code, college[1], None, None])

        return colleges


    @staticmethod
    def get_total():
        """Return the number of registered colleges."""
        
        query = '''SELECT * FROM college'''
        
        cursor.execute(query)
        result = cursor.fetchall()
        total = len(result)
        return total


    def college_list(self):
        """Return all registered colleges."""
        
        query = '''
            SELECT code, name
            FROM college
        '''
        
        cursor.execute(query)
        result = cursor.fetchall()
        colleges = [list(college) for college in result]
        return colleges


    @staticmethod
    def get_departments():
        """Return a list of courses grouped together by college name"""
        
        query = '''
            SELECT college.code, course.name
            FROM college
            JOIN course
            ON college.code = course.college
        '''
        
        cursor.execute(query)
        result = cursor.fetchall()
        departments = [list(department) for department in result]
        return departments


    def search(self, keyword: str = None, field: str = None):
        keyword = keyword.upper()
        colleges = self.get_all(paginate=False)

        result = []
        if field is None: 
            result = self.search_by_field(colleges, keyword, 'all')
        elif field == 'code':
            result = self.search_by_field(colleges, keyword, 'code')
        elif field == 'name':
            result = self.search_by_field(colleges, keyword, 'name')

        return result


    @staticmethod
    def search_by_field(rows: list = None, keyword: str = None, field: str = None):
        result = []
        for row in rows:
            row_allcaps = [str(cell).upper() for cell in row]

            if field == 'all':
                if keyword in row_allcaps:
                    result.append(row)
            if field == 'code':
                if keyword == row_allcaps[0]:
                    result.append(row)
                    return result
            elif field == 'name':
                if keyword == row_allcaps[1]:
                    result.append(row)

        return result


    def add_new(self):
        query = f'''
            INSERT INTO college (
                code,
                name
            )
            VALUES (
                '{self.code}',
                '{self.name}'
            )
        '''
        
        cursor.execute(query)
        db.commit()
        return None
    

    @staticmethod
    def delete(code: str = None):
        query = f'''
            DELETE FROM college
            WHERE code='{code}'
        '''
        
        cursor.execute(query)
        db.commit()
        return None


    def update(self):
        query = f'''
            UPDATE college
            SET 
                code = '{self.code}',
                name = '{self.name}'
            WHERE
                code = '{self.code}'
        '''

        cursor.execute(query)
        db.commit()
        return None


    @staticmethod
    def get_collegecode_for(course_name: str = None):
        query = f'''
            SELECT code
            FROM college
            WHERE name = '{course_name}'
        '''

        cursor.execute(query)
        code = cursor.fetchone()[0]
        return code


    @staticmethod
    def get_collegecodes():
        """Return all college codes"""
        
        query = '''
            SELECT code
            FROM college
        '''
        
        cursor.execute(query)
        result = cursor.fetchall()
        CODES = [code[0] for code in result]
        return CODES

ssis/views/colleges/__init__.py
from flask import Blueprint

college = Blueprint('college', __name__)

from . import routes

ssis/views/colleges/routes.py
from flask import request, render_template, redirect, flash
from flask.helpers import url_for
from ssis.models.student import Student
from ssis.models.course import Course
from ssis.models.college import College
from .utils import add_college_to_db, update_college_record
from . import college
from math import ceil

current_page = 1

@college.route('/colleges', methods=['GET', 'POST'])
def colleges() -> str:
    students = Student().get_all(paginate=False)
    courses = Course().get_all(paginate=False)
    colleges = College().get_all(current_page, 5)
    departments = College().get_departments()
    colleges_count = len(colleges)
    return render_template('/college/colleges.html', 
                            data=[students,courses,colleges,departments], 
                            datacount=f'{colleges_count} Colleges'
                           )


@college.route('/colleges/next', methods=['GET', 'POST'])
def next() -> str:
    global current_page
    college_count = College().get_total()
    current_page += 1
    limit_page = ceil(college_count/5)
    max_page_reached = current_page > limit_page

    if not max_page_reached:
        return redirect(url_for('college.colleges', page_num=current_page))
    else:
        current_page -= 1
        return redirect(url_for('college.colleges', page_num=current_page, limit=True))



@college.route('/colleges/prev', methods=['GET', 'POST'])
def prev() -> str:
    global current_page
    college_count = College().get_total()
    current_page -= 1
    max_page_reached = current_page <1

    if not max_page_reached:
        return redirect(url_for('college.colleges', page_num=current_page))
    else:
        current_page = 1
        return redirect(url_for('college.colleges', page_num=current_page, limit=True))



@college.route('/colleges/add', methods=['GET', 'POST'])
def add() -> str:
    if request.method == 'POST':
        college = {
            'code': request.form.get('college-code'),
            'name': request.form.get('college-name')
        }
        add_college_to_db(college)
        flash(f'{college["code"]} added succesfully!', 'info')
        return redirect(url_for('college.colleges'))
    else:
        return redirect(url_for('college.colleges'))


@college.route('/colleges/search', methods=['GET', 'POST'])
def search() -> str:
    user_input = request.form.get('user-input')
    field = request.form.get('field')

    if field == 'select':
        result = College().search(keyword=user_input)
    elif field == 'code':
        result = College().search(keyword=user_input, field='code')
    elif field == 'name':
        result = College().search(keyword=user_input, field='name')
    elif field == 'coursecount':
        result = College().search(keyword=user_input, field='coursecount')
    elif field == 'studentcount':
        result = College().search(keyword=user_input, field='studentcount')
    else:
        result = []

    if len(result) != 0:
        return render_template('/college/colleges.html', 
                                data=['', '', result], 
                                datacount= str(len(result)))
    else:
        flash(f'No college found', 'info')
        return render_template('/college/colleges.html', 
                                data=['', '', result], 
                                datacount= str(len(result)))


@college.route('/colleges/delete/<string:id>')
def delete(id: str) -> str:
    try:
        College().delete(id)
        flash(f'{id} deleted from the database.', 'info')
        return redirect(url_for('college.colleges'))
    except:
        flash(f'{id} cannot be deleted. Students or courses are registered under the selected college.', 'info')
        return redirect(url_for('college.colleges'))


@college.route('/colleges/update/<string:id>', methods=['GET', 'POST'])
def update(id: str) -> str:
    if request.method == 'POST':
        college = {
            'code': id,
            'name': request.form.get('college-name')
        }
        update_college_record(college)
        flash(f"{id} has been updated succesfully!", 'info')
        return redirect(url_for('college.colleges'))
    else:
        return redirect(url_for('college.colleges'))

ssis/templates/college/colleges.html
{% extends "base.html" %}

{% block title %}
<title>Colleges</title>
{% endblock %}

{% block navigation %}
<div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item" id="btn-student">
            <a href="{{url_for('student.students')}}" class="nav-link">Students</a>
        </li>
        <li class="nav-item" id="btn-courses">
            <a href="{{url_for('course.courses')}}" class="nav-link">Courses</a>
        </li>
        <li class="nav-item active" id="btn-colleges">
            <a href="{{url_for('college.colleges')}}" class="nav-link active" id="activeLink">Colleges</a>
        </li>
    </ul>
</div>
{% endblock %}

{% block table %}
<table class="table table-hover caption-top table-responsive-xl">
    <caption>
        <div id="caption">
            <div class="d-flex align-items-center caption-upper">
                <h4 class="p-2" id="table-title">Colleges Information</h4>
                <button class="btn btn-primary" id="addNew" data-bs-toggle="modal" data-bs-target="#addCollegeForm"><img src="../static/images/addcollegeICON.png" alt="" id="addcollegeICON"></button>
            </div>
            <div>
                <form class="pt-3 pb-3 d-flex align-items-center caption-lower" method="post" action="{{url_for('college.search')}}">
                    <select id="field" name="field" class="form-select p-2">
                        <option value="select">Select Field</option>
                        <option value="code">College Code</option>
                        <option value="name">College Name</option>
                    
                    </select>
                    <input id="searchfield" type="text" class="p-2 m-2 searchfield" name="user-input" placeholder="Type to search using College Code, and College Name">
                    <button class="btn-search">
                        <div class="search">
                            <div class="icon"></div>
                        </div>
                    </button>
                </form>
            </div>
        </div>
        {% include "/includes/alert_message.html"%}
    </caption>

    <thead class="table-light">
        <tr>
            <th scope="col">Code</th>
            <th scope="col">Name</th>
            <th scope="col">ACTION</th>
        </tr>
    </thead>
    <tbody>
    {% for college in data[2] %}
        <tr data-bs-toggle="modal" data-bs-target="#CollegeDepartments{{college.0}}">
            <th><b>{{college.0}}</b></th>
            <td>{{college.1}}</td>
            <td>
                <a href="{{url_for('college.update', id=college.0)}}" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#editCollegeForm{{college.0}}">Update</a>
                <a href="{{url_for('college.delete', id=college.0)}}" class="btn btn-danger" onclick="return confirm('Are you sure you want to remove {{college.1}} ?')">Delete</a>
        </tr>
          <!-- edit_course Modal  -->
          <div class="modal fade" id="editCollegeForm{{college.0}}" data-bs-backdrop="static"
          data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel">
          <div class="modal-dialog">
          <div class="modal-content">
  
              <div class="modal-header">
                  <div class="d-flex">
                   
                      <h5 class="modal-title" id="courseformtitle">Edit College</h5>
                  </div>
                  <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
  
              <div class="modal-body">
                  <form action="{{ url_for('college.update', id=college.0) }}" class="needs-validation" method="post">
                      <div class="mb-3">
                          <label for="college-code" class="form-label">College Code</label>
                          <input type="collegeinfo" class="form-control" id="college-code" value="{{college.0}}" name="college-code" disabled>
                      </div>
                      <div class="mb-3">
                          <label for="college-name" class="form-label">college Name</label>
                          <input type="collegeinfo" class="form-control" id="college-name" value="{{college.1}}" name="college-name" required>
                      </div>
                      <div class="modal-footer">
                          <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Cancel</button>
                          <button class="btn btn-primary" type="submit" id="addCourseclicked">Save Changes</button>
                      </div>
                  </form>
              </div>
          </div>
          </div>
          </div>

          <!-- view_courses Modal  -->
          <div class="modal fade" id="CollegeDepartments{{college.0}}" data-bs-backdrop="static"
          data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel">
          <div class="modal-dialog">
          <div class="modal-content">
  
              <div class="modal-header">
                  <div class=" d-flex college-logo">
                      <div class="logo">
        
                      </div>
                  </div>
                  <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  {% for department in data[3] %}
                    {% if department.0 == college.0 %}
                        <p>{{department.1}}</p>
                    {% endif %}
                  {% endfor %}
              </div>
  
          </div>
          </div>
          </div>
    {% endfor %}
    </tbody>
    <!-- <tfoot>
        <tr>
            <td>
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                      
                      <form action="{{ url_for('college.prev') }}" method="post">
                        <li class="page-item">
                          <button type="submit" class="page-link" aria-label="Previous" name="previous">Previous</button>
                        </li>
                      </form>
                
                      <form action="{{ url_for('college.next') }}" method="post">
                        <li class="page-item">
                          <button type="submit" class="page-link"  aria-label="Next" name="next">Next</button>
                        </li>
                      </form>
                    </ul>
                </nav>
            </td>
        </tr>
    </tfoot> -->
</table>
{% endblock %}